version: '3.3'

services:
   wp_mysql_server:
     image: mysql:5.7
     platform: linux/x86_64
     restart: always
     volumes:
       - ./db_data:/var/lib/mysql
     ports:
       - "33061:3306"
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wp_wordpress_server:
     depends_on:
       - wp_mysql_server
     image: wordpress:latest
     restart: always
     volumes:
       - ./wordpress_data:/var/www/html
     ports:
       - "8001:80"
     environment:
       WORDPRESS_DB_HOST: wp_mysql_server:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
